### ISSUE TITLE
Delete by JobID not working for me

### ISSUE THREAD

**Issue by abhishekanne-zageno** [jobrunr/example-spring#2]
```
    @GetMapping(value = "/delete-job", produces = {MediaType.TEXT_PLAIN_VALUE})
    public String deleteJob(@RequestParam(value = "jobId") String jobId) {
        jobScheduler.delete(jobId);
        return "Job Deleted: " + jobId;

    }
```
----
I tried to add up in controller new method to delete the Job By Job ID ..... It getting executed but Job still showing scheduled in dashboard.

**Comment by rdehuyss** [comment]
Sorry, for the late reply - just saw the issue.

When you want to delete a Job, you need to change the input to a UUID. Now, you're deleting a recurring job which does not exist and thus does not throw an error. Your method should become:

```java
    @GetMapping(value = "/delete-job", produces = {MediaType.TEXT_PLAIN_VALUE})
    public String deleteJob(@RequestParam(value = "jobId") UUID jobId) { // note the UUID here instead of the String
        jobScheduler.delete(jobId);
        return "Job Deleted: " + jobId;
    }
```
